# config/packages/security.yaml
security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
       
    
    access_control :
        - {  path : ^/login$ ,  roles : IS_AUTHENTICATED_ANONYMOUSLY }
        - {  path : '^/list' ,  roles :  ROLE_USER}

    role_hierarchy :
        ROLE_ADMIN :       ROLE_USER
