#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_proj:
    path: /project
    controller: App\Controller\ProjectsController::createProject ()

app_tick:
    path: /tick
    controller: App\Controller\ProjectsController::createTick ()

app_creatProj:
    path: /createProj
    controller: App\Controller\ProjectController::new ()

app_register:
    path: /register
    controller: App\Controller\RegistrationController::registerAction ()

app_list:
    path: /list
    controller: App\Controller\ProjectController::listProj ()

app_editproj:
    path: /editProj
    controller: App\Controller\ProjectController::edit ()

app_projid:
    path: /project/{project}
    controller: App\Controller\ProjectController::show ()

app_projshow:
    path: /project/{id}
    controller: App\Controller\ProjectController::showt ()

app_edittick:
    path: /editTick/{id}
    controller: App\Controller\TicketController::edit ()

app_newtick:
    path: /newTick
    controller: App\Controller\TicketController::newt ()
#routing_distributed:
    # loads routes from the given routing file stored in some bundle
#    resource: '..\src\Resources\config\routing.yml' 
#   type: yaml




